### ISSUE TITLE
Issue with changing email

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/Elements#5]
I tried changing my email and it keeps giving me an "Invalid customer token" error message.

![screen shot 2017-09-27 at 1 24 19 pm 2](https://user-images.githubusercontent.com/11448089/30935983-42903b7e-a387-11e7-9954-41d056bb07bd.png)

**Comment by influxweb** [comment]
With the 9.7 update, it appears that a new token was added as a security measure. The code has been updated and the issue resolved. This also fixes #6 and fixes #7
