### ISSUE TITLE
double message

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/Elements#8]
When I signed up for an account it gave me a double message. 

<img width="1440" alt="screen shot 2017-10-05 at 1 07 48 pm" src="https://user-images.githubusercontent.com/11448089/31250058-73d7a300-a9ce-11e7-8800-93b53d85fa4f.png">

<img width="1440" alt="screen shot 2017-10-05 at 1 08 02 pm" src="https://user-images.githubusercontent.com/11448089/31250067-78e13cd0-a9ce-11e7-8af7-546737942315.png">

**Comment by influxweb** [comment]
Looks like the token which displays the message was listed twice on the page. The second one has been removed so only one message will show not. This also closes #3
